apiVersion: apps/v1
kind: Deployment
metadata:
  name: atualizar-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atualizar-worker
  template:
    metadata:
      labels:
        app: atualizar-worker
    spec:
      containers:
        - name: atualizar-worker
          image: rafaelssouza108/worker.atualizar:1.0
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_VHOST
            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_QUEUE
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
            - name: MONGO_CONNECTION
              value: mongodb://mongo:27017/test
